# uv 配置文件
# 使用清华镜像源加速下载

[pip]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[[index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[[index]]
url = "https://mirrors.aliyun.com/pypi/simple/"

